"""
outbox.py — Approval-gated send queue. The rails for outreach, built honestly.

The audit forbids automated sending before a supervised pilot and legal sign-off,
and there are no live email credentials here. So this builds the MECHANISM —
draft → human approval → send — with a stubbed sender that does not touch real
mail. Wiring a real sender is a deliberate, later step (see GmailSenderStub).

Guarantees enforced in code:
  • Nothing sends without an explicit human approval.
  • Nothing sends to a suppressed record — re-checked at approve AND at send.
  • A daily send cap (deliverability hygiene) is enforced.
  • Drafts are generated by the compliant outreach_generator, so the body
    already carries the free-claim disclosure and the 10% fee framing.

States:  DRAFT → APPROVED → SENT
                     └────→ HELD  (suppressed/blocked at send time)
"""
from __future__ import annotations

import sqlite3
from datetime import datetime, date
from pathlib import Path

from heirbud_crm import HeirBudCRM
from outreach_generator import generate_scripts, SuppressedProspectError

DAILY_CAP_DEFAULT = 50   # from the Email Template Library deliverability rules


# ── Sender adapters ──────────────────────────────────────────────────────────
class DryRunSender:
    """Default sender: records intent, sends nothing. Safe everywhere."""
    name = "dry-run"

    def send(self, to: str, channel: str, subject: str, body: str) -> str:
        return f"DRY-RUN: would send {channel} to {to or '(no address)'}"


class GmailSenderStub:
    """Placeholder for a real sender. Intentionally not implemented.

    Wiring this requires: OAuth credentials, a dedicated warmed domain, and —
    per the audit — legal sign-off on the templates and a supervised pilot
    first. Until then the outbox runs dry.
    """
    name = "gmail-stub"

    def send(self, to: str, channel: str, subject: str, body: str) -> str:
        raise NotImplementedError(
            "Live sending is not enabled. Provide a real Sender only after "
            "legal sign-off, credentials, and a supervised pilot.")


# ── Outbox ───────────────────────────────────────────────────────────────────
class Outbox:
    def __init__(self, crm: HeirBudCRM | None = None, db_path=None):
        if crm is not None:
            self.crm = crm
        elif db_path is not None:
            self.crm = HeirBudCRM(db_path=db_path)
        else:
            self.crm = HeirBudCRM()
        self.db_path = self.crm.db_path
        self._init()

    def _conn(self):
        c = sqlite3.connect(self.db_path)
        c.row_factory = sqlite3.Row
        return c

    def _init(self):
        with self._conn() as c:
            c.execute("""CREATE TABLE IF NOT EXISTS outbox (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                property_id TEXT NOT NULL,
                channel TEXT NOT NULL,
                to_addr TEXT,
                subject TEXT,
                body TEXT,
                status TEXT DEFAULT 'DRAFT',
                created_at TEXT,
                approved_at TEXT,
                approved_by TEXT,
                sent_at TEXT,
                send_result TEXT
            )""")

    # ── queue ────────────────────────────────────────────────────────────────
    def queue_draft(self, property_id: str, channel: str = "email") -> int:
        """Generate a compliant draft for a prospect and queue it as DRAFT.

        Refuses suppressed records outright (SuppressedProspectError bubbles up).
        """
        p = self.crm.get_prospect(property_id)
        if not p:
            raise ValueError(f"No prospect {property_id!r}")
        scripts = generate_scripts(p)   # raises if suppressed
        if channel == "email":
            body = scripts["cold_email"]
            subject, _, rest = body.partition("\n")
            subject = subject.replace("Subject:", "").strip()
            to_addr = p.get("email")
            body = rest.strip()
        elif channel == "sms":
            subject, body, to_addr = "", scripts["sms_opener"], p.get("phone")
        else:
            raise ValueError("channel must be 'email' or 'sms'")
        now = datetime.now().isoformat()
        with self._conn() as c:
            cur = c.execute("""INSERT INTO outbox
                (property_id, channel, to_addr, subject, body, status, created_at)
                VALUES (?,?,?,?,?, 'DRAFT', ?)""",
                (property_id, channel, to_addr, subject, body, now))
            return cur.lastrowid

    # ── approve ──────────────────────────────────────────────────────────────
    def approve(self, outbox_id: int, approver: str) -> bool:
        """Human approval. Re-checks suppression; refuses if opted out."""
        row = self._get(outbox_id)
        if not row or row["status"] != "DRAFT":
            return False
        p = self.crm.get_prospect(row["property_id"])
        if not p or p.get("suppression_status") == "SUPPRESSED":
            self._set_status(outbox_id, "HELD", result="suppressed at approval")
            return False
        with self._conn() as c:
            c.execute("UPDATE outbox SET status='APPROVED', approved_at=?, approved_by=? "
                      "WHERE id=?", (datetime.now().isoformat(), approver, outbox_id))
        return True

    # ── send ─────────────────────────────────────────────────────────────────
    def send_approved(self, sender=None, daily_cap: int = DAILY_CAP_DEFAULT) -> dict:
        """Send everything APPROVED, up to the daily cap. Suppressed → HELD.

        Only APPROVED rows are eligible — a DRAFT can never be sent. Suppression
        is re-checked one last time immediately before each send.
        """
        sender = sender or DryRunSender()
        sent, held, capped = 0, 0, 0
        already = self._sent_today()
        with self._conn() as c:
            rows = c.execute("SELECT * FROM outbox WHERE status='APPROVED' "
                             "ORDER BY approved_at").fetchall()
        for row in rows:
            if already + sent >= daily_cap:
                capped += 1
                continue
            p = self.crm.get_prospect(row["property_id"])
            if not p or p.get("suppression_status") == "SUPPRESSED":
                self._set_status(row["id"], "HELD", result="suppressed at send")
                held += 1
                continue
            result = sender.send(row["to_addr"], row["channel"], row["subject"], row["body"])
            self._set_status(row["id"], "SENT", result=f"[{sender.name}] {result}",
                             sent=True)
            self.crm.log_contact_attempt(row["property_id"], row["channel"].title(),
                                         "Sent", f"outbox #{row['id']}: {result}")
            sent += 1
        return {"sent": sent, "held": held, "capped": capped,
                "cap": daily_cap, "already_sent_today": already}

    # ── helpers ──────────────────────────────────────────────────────────────
    def _get(self, outbox_id: int):
        with self._conn() as c:
            return c.execute("SELECT * FROM outbox WHERE id=?", (outbox_id,)).fetchone()

    def _set_status(self, outbox_id: int, status: str, result: str = "", sent: bool = False):
        fields = "status=?, send_result=?"
        args = [status, result]
        if sent:
            fields += ", sent_at=?"
            args.append(datetime.now().isoformat())
        args.append(outbox_id)
        with self._conn() as c:
            c.execute(f"UPDATE outbox SET {fields} WHERE id=?", args)

    def _sent_today(self) -> int:
        today = date.today().isoformat()
        with self._conn() as c:
            row = c.execute("SELECT COUNT(*) n FROM outbox WHERE status='SENT' "
                            "AND sent_at LIKE ?", (today + "%",)).fetchone()
        return row["n"]

    def list_outbox(self, status: str | None = None) -> list[dict]:
        q = "SELECT * FROM outbox"
        args = []
        if status:
            q += " WHERE status=?"
            args.append(status)
        q += " ORDER BY id"
        with self._conn() as c:
            return [dict(r) for r in c.execute(q, args).fetchall()]


if __name__ == "__main__":
    import tempfile, os
    db = os.path.join(tempfile.mkdtemp(), "demo.db")
    crm = HeirBudCRM(db_path=db)
    crm.add_prospect({"property_id": "X1", "name": "Ann Sample", "amount": 40000,
                      "holder": "EXAMPLE BANK", "email": "ann@example.com"})
    ob = Outbox(crm)
    i = ob.queue_draft("X1", "email")
    print("queued draft", i, "| approve ->", ob.approve(i, "zack"))
    print("send ->", ob.send_approved())
    print("statuses ->", [(r["id"], r["status"]) for r in ob.list_outbox()])
